name: kanza
description: make to-do like Kanza

version: 0.0.1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.2.4
  flutter_bloc: ^6.0.1
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.18.1
  google_fonts: ^1.1.0
  intl: ^0.16.1
  moor_flutter: ^3.1.0
  path_provider: ^1.6.14
  shared_preferences: ^0.5.10

dependency_overrides:
  pedantic: 1.8.0
  analyzer: 0.39.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  moor_generator: ^3.3.1
  pedantic: ^1.9.2
  recase: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/langs/
