name: kanza
description: make to-do like Kanza

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  flutter_bloc: ^6.0.1
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  path_provider: ^1.6.14  
  flutter_svg: ^0.18.1
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3

dependency_overrides:
    pedantic: 1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner:
  recase: ^3.0.0  
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/langs/

