name: kanza
description: make to-do like Kanza

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  flutter_bloc: ^6.0.1
  equatable: ^1.2.4
  path_provider: ^1.6.14  
  flutter_svg: ^0.18.1
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  moor_flutter: ^3.1.0
  shared_preferences: ^0.5.10

dependency_overrides:
    pedantic: 1.8.0
    analyzer: 0.39.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^3.3.1
  recase: ^3.0.0  
  pedantic: ^1.9.2


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/langs/

