name: kanza
description: make to-do like Kanza

version: 0.0.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ansicolor: ^1.1.1
  cupertino_icons: ^0.1.3
  equatable: ^1.2.4
  flutter_bloc: ^6.0.1
  flutter_svg: ^0.18.1
  google_fonts: ^1.1.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  logging: ^0.11.4

dependency_overrides:
  pedantic: 1.8.0
  analyzer: 0.39.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  hive_generator: ^0.8.2
  moor_generator: ^3.3.1
  pedantic: ^1.9.2
  recase: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
